/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ImageAnalyzeTool */

#ifndef _Included_ImageAnalyzeTool
#define _Included_ImageAnalyzeTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ImageAnalyzeTool
 * Method:    analyze
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ImageAnalyzeTool_analyze
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
