/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_champer_imageanalyze_ImageAnalyzeTool */

#ifndef _Included_com_champer_imageanalyze_ImageAnalyzeTool
#define _Included_com_champer_imageanalyze_ImageAnalyzeTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_champer_imageanalyze_ImageAnalyzeTool
 * Method:    analyze
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_champer_imageanalyze_ImageAnalyzeTool_analyze
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_champer_imageanalyze_ImageAnalyzeTool
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_champer_imageanalyze_ImageAnalyzeTool_init
  (JNIEnv *, jobject);

/*
 * Class:     com_champer_imageanalyze_ImageAnalyzeTool
 * Method:    release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_champer_imageanalyze_ImageAnalyzeTool_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
